-- 01_setup.sql
CREATE WAREHOUSE IF NOT EXISTS HEALTH_DW_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS DEV_HEALTH_DB;
CREATE DATABASE IF NOT EXISTS QA_HEALTH_DB;
CREATE DATABASE IF NOT EXISTS PROD_HEALTH_DB;

CREATE SCHEMA IF NOT EXISTS DEV_HEALTH_DB.RAW;
CREATE SCHEMA IF NOT EXISTS DEV_HEALTH_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS DEV_HEALTH_DB.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS DEV_HEALTH_DB.SNAPSHOT;
CREATE SCHEMA IF NOT EXISTS DEV_HEALTH_DB.MART;
CREATE SCHEMA IF NOT EXISTS DEV_HEALTH_DB.SECURITY;

CREATE FILE FORMAT IF NOT EXISTS DEV_HEALTH_DB.RAW.FF_CSV
  TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE FILE FORMAT IF NOT EXISTS DEV_HEALTH_DB.RAW.FF_JSON TYPE = JSON;
CREATE FILE FORMAT IF NOT EXISTS DEV_HEALTH_DB.RAW.FF_PARQUET TYPE = PARQUET;
CREATE FILE FORMAT IF NOT EXISTS DEV_HEALTH_DB.RAW.FF_AVRO TYPE = AVRO;
CREATE FILE FORMAT IF NOT EXISTS DEV_HEALTH_DB.RAW.FF_ORC TYPE = ORC;
