-- 02_raw_tables.sql
-- RAW preserves source-like values and adds ingestion lineage metadata.
-- No business transformations belong in RAW.

USE WAREHOUSE HEALTH_DW_WH;

CREATE OR REPLACE TABLE DEV_HEALTH_DB.RAW.PATIENTS (
    PATIENT_ID        VARCHAR,
    FIRST_NAME        VARCHAR,
    LAST_NAME         VARCHAR,
    DATE_OF_BIRTH     DATE,
    GENDER            VARCHAR,
    ADDRESS           VARCHAR,
    CITY              VARCHAR,
    COUNTRY           VARCHAR,
    POSTCODE          VARCHAR,
    PATIENT_TYPE      VARCHAR,
    CREATED_DATE      DATE,
    SOURCE_SYSTEM     VARCHAR,
    SOURCE_TABLE      VARCHAR,
    BATCH_ID          VARCHAR,
    FILE_NAME         VARCHAR,
    INGESTED_AT       TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DEV_HEALTH_DB.RAW.PROVIDERS (
    PROVIDER_ID       VARCHAR,
    PROVIDER_NAME     VARCHAR,
    SPECIALTY         VARCHAR,
    FACILITY          VARCHAR,
    SOURCE_SYSTEM     VARCHAR,
    SOURCE_TABLE      VARCHAR,
    BATCH_ID          VARCHAR,
    FILE_NAME         VARCHAR,
    INGESTED_AT       TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DEV_HEALTH_DB.RAW.INSURANCE (
    INSURANCE_ID      VARCHAR,
    PATIENT_ID        VARCHAR,
    PAYER_NAME        VARCHAR,
    POLICY_NUMBER     VARCHAR,
    EFFECTIVE_DATE    DATE,
    EXPIRY_DATE       DATE,
    STATUS            VARCHAR,
    SOURCE_SYSTEM     VARCHAR,
    SOURCE_TABLE      VARCHAR,
    BATCH_ID          VARCHAR,
    FILE_NAME         VARCHAR,
    INGESTED_AT       TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DEV_HEALTH_DB.RAW.APPOINTMENTS (
    APPOINTMENT_ID    VARCHAR,
    PATIENT_ID        VARCHAR,
    PROVIDER_ID       VARCHAR,
    APPOINTMENT_TS    TIMESTAMP_NTZ,
    STATUS            VARCHAR,
    APPOINTMENT_TYPE  VARCHAR,
    SOURCE_SYSTEM     VARCHAR,
    SOURCE_TABLE      VARCHAR,
    BATCH_ID          VARCHAR,
    FILE_NAME         VARCHAR,
    INGESTED_AT       TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DEV_HEALTH_DB.RAW.CLINICAL_RECORDS (
    CLINICAL_ID       VARCHAR,
    PATIENT_ID        VARCHAR,
    PROVIDER_ID       VARCHAR,
    RECORD_DATE       DATE,
    DIAGNOSIS         VARCHAR,
    CLINICAL_STATUS   VARCHAR,
    SOURCE_SYSTEM     VARCHAR,
    SOURCE_TABLE      VARCHAR,
    BATCH_ID          VARCHAR,
    FILE_NAME         VARCHAR,
    INGESTED_AT       TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DEV_HEALTH_DB.RAW.CLAIMS (
    CLAIM_ID          VARCHAR,
    PATIENT_ID        VARCHAR,
    PROVIDER_ID       VARCHAR,
    SERVICE_DATE      DATE,
    CLAIM_STATUS      VARCHAR,
    BILLED_AMOUNT     NUMBER(18,2),
    PAID_AMOUNT       NUMBER(18,2),
    BALANCE_AMOUNT    NUMBER(18,2),
    SOURCE_SYSTEM     VARCHAR,
    SOURCE_TABLE      VARCHAR,
    BATCH_ID          VARCHAR,
    FILE_NAME         VARCHAR,
    INGESTED_AT       TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DEV_HEALTH_DB.RAW.BILLING (
    BILLING_ID        VARCHAR,
    CLAIM_ID          VARCHAR,
    PATIENT_ID        VARCHAR,
    BILLING_DATE      DATE,
    BILLED_AMOUNT     NUMBER(18,2),
    BILLING_STATUS    VARCHAR,
    SOURCE_SYSTEM     VARCHAR,
    SOURCE_TABLE      VARCHAR,
    BATCH_ID          VARCHAR,
    FILE_NAME         VARCHAR,
    INGESTED_AT       TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DEV_HEALTH_DB.RAW.PAYMENTS (
    PAYMENT_ID        VARCHAR,
    CLAIM_ID          VARCHAR,
    PATIENT_ID        VARCHAR,
    PAYMENT_DATE      DATE,
    PAYMENT_AMOUNT    NUMBER(18,2),
    PAYMENT_METHOD    VARCHAR,
    SOURCE_SYSTEM     VARCHAR,
    SOURCE_TABLE      VARCHAR,
    BATCH_ID          VARCHAR,
    FILE_NAME         VARCHAR,
    INGESTED_AT       TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DEV_HEALTH_DB.RAW.DOCTOR_ASSIGNMENTS (
    ASSIGNMENT_ID     VARCHAR,
    PATIENT_ID        VARCHAR,
    PROVIDER_ID       VARCHAR,
    EFFECTIVE_DATE    DATE,
    ASSIGNMENT_TYPE   VARCHAR,
    SOURCE_SYSTEM     VARCHAR,
    SOURCE_TABLE      VARCHAR,
    BATCH_ID          VARCHAR,
    FILE_NAME         VARCHAR,
    INGESTED_AT       TIMESTAMP_NTZ
);
