-- 03_cdc_streams_tasks.sql
CREATE OR REPLACE STREAM DEV_HEALTH_DB.RAW.CLAIMS_STREAM
  ON TABLE DEV_HEALTH_DB.RAW.CLAIMS
  APPEND_ONLY = FALSE;

CREATE OR REPLACE TASK DEV_HEALTH_DB.RAW.TASK_PROCESS_CLAIMS
  WAREHOUSE = HEALTH_DW_WH
  SCHEDULE = 'USING CRON 0 * * * * UTC'
  WHEN SYSTEM$STREAM_HAS_DATA('DEV_HEALTH_DB.RAW.CLAIMS_STREAM')
AS
MERGE INTO DEV_HEALTH_DB.STAGING.CLAIMS_INCREMENTAL tgt
USING (
  SELECT CLAIM_ID, PATIENT_ID, PROVIDER_ID, SERVICE_DATE, CLAIM_STATUS,
         BILLED_AMOUNT, PAID_AMOUNT, BALANCE_AMOUNT, INGESTED_AT
  FROM DEV_HEALTH_DB.RAW.CLAIMS_STREAM
  WHERE METADATA$ACTION IN ('INSERT','DELETE','UPDATE')
) src
ON tgt.CLAIM_ID = src.CLAIM_ID
WHEN MATCHED AND src.BALANCE_AMOUNT <> tgt.BALANCE_AMOUNT THEN
  UPDATE SET
    CLAIM_STATUS = src.CLAIM_STATUS,
    BILLED_AMOUNT = src.BILLED_AMOUNT,
    PAID_AMOUNT = src.PAID_AMOUNT,
    BALANCE_AMOUNT = src.BALANCE_AMOUNT,
    INGESTED_AT = src.INGESTED_AT
WHEN NOT MATCHED THEN
  INSERT (CLAIM_ID, PATIENT_ID, PROVIDER_ID, SERVICE_DATE, CLAIM_STATUS,
          BILLED_AMOUNT, PAID_AMOUNT, BALANCE_AMOUNT, INGESTED_AT)
  VALUES (src.CLAIM_ID, src.PATIENT_ID, src.PROVIDER_ID, src.SERVICE_DATE,
          src.CLAIM_STATUS, src.BILLED_AMOUNT, src.PAID_AMOUNT,
          src.BALANCE_AMOUNT, src.INGESTED_AT);

ALTER TASK DEV_HEALTH_DB.RAW.TASK_PROCESS_CLAIMS RESUME;
