-- 04_security.sql
CREATE ROLE IF NOT EXISTS HEALTH_ADMIN;
CREATE ROLE IF NOT EXISTS HEALTH_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS HEALTH_ANALYST;
CREATE ROLE IF NOT EXISTS HEALTH_BI_READER;

CREATE OR REPLACE MASKING POLICY DEV_HEALTH_DB.SECURITY.MASK_PATIENT_NAME
AS (VAL STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('HEALTH_ADMIN','HEALTH_DATA_ENGINEER') THEN VAL
    ELSE '***MASKED***'
  END;

ALTER TABLE DEV_HEALTH_DB.MART.DIM_PATIENT
  ALTER COLUMN FIRST_NAME SET MASKING POLICY DEV_HEALTH_DB.SECURITY.MASK_PATIENT_NAME;

ALTER TABLE DEV_HEALTH_DB.MART.DIM_PATIENT
  ALTER COLUMN LAST_NAME SET MASKING POLICY DEV_HEALTH_DB.SECURITY.MASK_PATIENT_NAME;

-- Extend this pattern to DOB, address, postcode, policy number, and other PHI/PII.
