-- External/internal stage patterns and file formats
CREATE FILE FORMAT IF NOT EXISTS DEV_HEALTH_DB.RAW.FF_TXT TYPE = CSV FIELD_DELIMITER = NONE SKIP_HEADER = 0;
CREATE FILE FORMAT IF NOT EXISTS DEV_HEALTH_DB.RAW.FF_JSON TYPE = JSON;
CREATE FILE FORMAT IF NOT EXISTS DEV_HEALTH_DB.RAW.FF_PARQUET TYPE = PARQUET;
CREATE FILE FORMAT IF NOT EXISTS DEV_HEALTH_DB.RAW.FF_AVRO TYPE = AVRO;
CREATE FILE FORMAT IF NOT EXISTS DEV_HEALTH_DB.RAW.FF_ORC TYPE = ORC;

-- Example internal stage. For cloud landing, use an external stage with a storage integration.
CREATE OR REPLACE STAGE DEV_HEALTH_DB.RAW.HEALTH_LANDING_STAGE;

-- Example CSV load pattern
-- COPY INTO DEV_HEALTH_DB.RAW.PATIENTS
-- FROM @DEV_HEALTH_DB.RAW.HEALTH_LANDING_STAGE/patients/
-- FILE_FORMAT = DEV_HEALTH_DB.RAW.FF_CSV
-- ON_ERROR = 'ABORT_STATEMENT';
