-- 06_audit_control.sql
CREATE SCHEMA IF NOT EXISTS DEV_HEALTH_DB.AUDIT;

CREATE OR REPLACE TABLE DEV_HEALTH_DB.AUDIT.BATCH_AUDIT (
    BATCH_ID              VARCHAR,
    SOURCE_SYSTEM         VARCHAR,
    SOURCE_TABLE          VARCHAR,
    FILE_NAME             VARCHAR,
    EXTRACT_STARTED_AT    TIMESTAMP_NTZ,
    EXTRACT_COMPLETED_AT  TIMESTAMP_NTZ,
    SOURCE_ROW_COUNT      NUMBER,
    RAW_ROW_COUNT         NUMBER,
    TARGET_ROW_COUNT      NUMBER,
    SOURCE_AMOUNT         NUMBER(18,2),
    TARGET_AMOUNT         NUMBER(18,2),
    LOAD_STATUS           VARCHAR,
    ERROR_MESSAGE         VARCHAR,
    CREATED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DEV_HEALTH_DB.AUDIT.DBT_RUN_AUDIT (
    INVOCATION_ID         VARCHAR,
    MODEL_NAME            VARCHAR,
    STATUS                VARCHAR,
    EXECUTED_AT           TIMESTAMP_NTZ,
    ROW_COUNT             NUMBER,
    ERROR_MESSAGE         VARCHAR
);
