-- Example stored procedure for batch audit status
CREATE OR REPLACE PROCEDURE DEV_HEALTH_DB.AUDIT.SP_CLOSE_BATCH(BATCH_ID_INPUT VARCHAR, STATUS_INPUT VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
  UPDATE DEV_HEALTH_DB.AUDIT.BATCH_AUDIT
     SET LOAD_STATUS = :STATUS_INPUT
   WHERE BATCH_ID = :BATCH_ID_INPUT;
  RETURN 'Batch status updated';
END;
$$;

-- Example UDF: denial flag
CREATE OR REPLACE FUNCTION DEV_HEALTH_DB.AUDIT.IS_DENIED(CLAIM_STATUS_INPUT VARCHAR)
RETURNS BOOLEAN
LANGUAGE SQL
AS
$$
  UPPER(CLAIM_STATUS_INPUT) = 'DENIED'
$$;
