version: 2

sources:
  - name: raw
    database: "{{ target.database }}"
    schema: RAW
    tables:
      - name: patients
      - name: providers
      - name: insurance
      - name: appointments
      - name: clinical_records
      - name: claims
      - name: billing
      - name: payments
      - name: doctor_assignments
